### ISSUE TITLE
Remove node_modules

### ISSUE THREAD

**Issue by Marlysson** [IgorDePaula/Restaurante#1]
Replace node_modules folder by package json dependences, and install them run npm install

**Comment by IgorDePaula** [comment]
I'm not understand you.

**Comment by Marlysson** [comment]
Falar em pt-br :smile: 

Só uma questão de organização mesmo , que no seu projeto tem a pasta bower_components ( me confundi com a node_modules ( mals ) ) , e que você podia substituir ela pelo arquivo package.json ou um bower.json da vida , listando as dependência do projeto , e só daria um :
```npm install``` ou ```bower install``` no arquivo das dependências.

**Comment by IgorDePaula** [comment]
Ah, show, este foi um repo de experiencia, nada serio.

Em 20 de dezembro de 2016 11:50, Marlysson Silva <notifications@github.com>
escreveu:
